### ISSUE TITLE
tqdm(data) error

### ISSUE THREAD

**Issue by shuxp** [ypwhs/DogBreed_gluon#1]
my code went error when running `for X,y in tqdm(data)` 
I have installed all dependence. But went error like following
`
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
`

Have you ever met this error before?Thanks.

**Comment by ypwhs** [comment]
你可以买两根 32G 的内存条，插到电脑上，重启，重新运行代码，也可以用 gluon 的 ImageFolderDataset。

**Comment by shuxp** [comment]
关键我用的是腾讯云的云主机。。会有影响嘛

**Comment by ypwhs** [comment]
那你可以开个 aws p2.xlarge 或者 p3，60G 内存够用了，这个项目需要大概 40G 内存。

**Comment by shuxp** [comment]
这样啊，我的内存56G，估计硬盘不够，硬盘只有50G，我换个大点的硬盘试试，谢啦
